---
- name: Enable nested virt on ec2 instances
  hosts: "{{ _hosts | default(omit) }}"
  gather_facts: false

  tasks:
    - name: Include nested virt role
      ansible.builtin.include_role:
        name: "demo.cloud.aws"
        tasks_from: enable_virt_ec2.yml
