---
- name: Listen for external webhook events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        # Optional: Define security if supported by your provider
        # hmac_secret: "your_shared_secret" 
        # hmac_header: "X-Hub-Signature-256"

  rules:
    - name: Trigger Rocket Remeidation Template
      condition: event.payload.message == "FIRE 1"
      action:
        run_job_template:
          name: "LINUX | Patching"
          organization: "Ansible Product Demos (APD)"
          job_args:
            extra_vars:
              _hosts: aws_rhel9
