---
- name: Create a Nested VM on a RHEL Host
  hosts: "{{ _hosts | default(omit)  }}"
  become: true

  vars:
    host_port: "{{ _host_port | default(80) }}"
    vm_port: "{{ _vm_port | default(80) }}"

  tasks:
    - name: Check for vars
      ansible.builtin.assert:
        that:
          - vm_name is defined
          - vm_name != ''
          - vm_name != 'undef'
          - vm_os_image is defined
          - vm_os_image != ''
          - vm_os_image != 'undef'

    - name: Ensure libvirt is installed
      ansible.builtin.dnf:
        name:
          - libvirt
          - qemu-kvm
          - libguestfs-tools
          - python3-libvirt
          - virt-install
          - python3-lxml
          - guestfs-tools
          - firewalld
        state: present

    - name: Ensure libvirtd service is running and enabled
      ansible.builtin.service:
        name: libvirtd
        state: started
        enabled: true

    - name: Ensure firewalld service is running and enabled
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Add user to libvirt group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: libvirt
        append: true

    - name: Download VM OS Image
      ansible.builtin.get_url:
        url: "{{ vm_os_image }}"
        dest: "/tmp/my_os_image.qcow2"
        mode: "0644"

    - name: Copy image to libvirt directory
      ansible.builtin.copy:
        src: "/tmp/my_os_image.qcow2"
        dest: "/var/lib/libvirt/images/{{ vm_name }}.qcow2"
        remote_src: true
        owner: qemu
        group: qemu
        mode: "0660"
      register: copy_results

    - name: Check if the VM is already defined
      ansible.builtin.command:
        cmd: "virsh dominfo {{ vm_name }}"
      register: vm_definition_check
      failed_when: false
      changed_when: false

    - name: Define the VM
      ansible.builtin.template:
        src: "templates/nested_vm_def.xml.j2"
        dest: "/tmp/{{ vm_name }}.xml"
        owner: root
        group: root
        mode: "0644"

    # NOTE: Through out this playbook we are not using community.libvirt.virt
    # module because it isn't in the stock supported-ee collections.
    - name: Define the VM in libvirt using virsh
      ansible.builtin.command:
        cmd: "virsh define /tmp/{{ vm_name }}.xml"
      when: vm_definition_check.rc != 0
      register: vm_define_result
      changed_when: vm_define_result.rc == 0

    - name: Check if the VM is already started
      ansible.builtin.command:
        cmd: "virsh domstate {{ vm_name }}"
      register: vm_state_check
      failed_when: false
      changed_when: false

    - name: Start the VM
      ansible.builtin.command:
        cmd: "virsh start {{ vm_name }}"
      when: vm_state_check.stdout | trim != 'running'
      register: vm_start_result
      changed_when: vm_start_result.rc == 0

    - name: Gather DHCP IP address of the VM
      ansible.builtin.command: >
        virsh domifaddr --domain {{ vm_name }}
      register: virsh_output
      changed_when: false
      until: virsh_output.stdout_lines | length >= 3
      retries: 5
      delay: 5

    - name: Parse and set the VM IP address from virsh output
      ansible.builtin.set_fact:
        vm_ip: "{{ virsh_output.stdout_lines[2] | regex_search('[0-9]{1,3}(?:[.][0-9]{1,3}){3}') }}"
        vm_mac: "{{ virsh_output.stdout_lines[2] | regex_search('([0-9a-fA-F]{2}[:-]){5}([0-9a-fA-F]{2})') }}"

    - name: Fail if VM IP address could not be found
      ansible.builtin.fail:
        msg: "Could not find a DHCP IP address for VM: {{ vm_name }}. Ensure the VM is running."
      when: vm_ip is none or vm_ip == ""

    - name: Fail if VM MAC address could not be found
      ansible.builtin.fail:
        msg: "Could not find a MAC address for VM: {{ vm_name }}. Ensure the VM is running."
      when: vm_mac is none or vm_mac == ""

    - name: Get default libvirt network configuration to check for existing DHCP host reservation
      ansible.builtin.command: >
        virsh net-dumpxml default
      register: dhcp_reservation_check
      failed_when: false
      changed_when: false

    - name: Build the expected DHCP host reservation XML
      ansible.builtin.set_fact:
        expected_dhcp_reservation: "<host mac='{{ vm_mac }}' name='{{ vm_name }}' ip='{{ vm_ip }}'/>"

    - name: Set fact for if the static DHCP host reservation already exists
      ansible.builtin.set_fact:
        vm_reservation_exists: "{{ dhcp_reservation_check.stdout.find(expected_dhcp_reservation) != -1 }}"

    - name: Add static DHCP host reservation to libvirt network live
      ansible.builtin.command: >
        virsh net-update default add ip-dhcp-host "{{ expected_dhcp_reservation }}" --live --config
      register: virsh_update
      failed_when:
        - virsh_update.rc != 0
        - "'already exists' not in virsh_update.stderr"
      changed_when: virsh_update.rc == 0
      when: not vm_reservation_exists

    - name: Create Libvirt Hook Directory
      ansible.builtin.file:
        path: "/etc/libvirt/hooks"
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Create Libvirt Hook for QEMU to create iptables rules
      ansible.builtin.template:
        src: "templates/qemu.j2"
        dest: "/etc/libvirt/hooks/qemu"
        mode: "0755"
        owner: root
        group: root
      register: hook_template_result

    - name: Restart Virt Stack
      when: hook_template_result.changed or vm_define_result.changed or vm_start_result.changed
      block:
        - name: Stop VM # noqa: command-instead-of-module no-changed-when
          ansible.builtin.command:
            cmd: "virsh destroy {{ vm_name }}"

        - name: Stop libvirt
          ansible.builtin.service:
            name: libvirtd
            state: stopped

        - name: Start libvirt
          ansible.builtin.service:
            name: libvirtd
            state: started

        - name: Start VM # noqa: command-instead-of-module no-changed-when
          ansible.builtin.command:
            cmd: "virsh start {{ vm_name }}"
