---
- name: Create a Nested VM on a RHEL Host
  hosts: "{{ _hosts | default(omit)  }}"
  become: true

  vars:
    host_port: "{{ _host_port | default(8080) }}"
    vm_port: "{{ _vm_port | default(80) }}"

  tasks:
    - name: Check for vars
      ansible.builtin.assert:
        that:
          - vm_name is defined
          - vm_name != ''
          - vm_name != 'undef'
          - vm_os_image is defined
          - vm_os_image != ''
          - vm_os_image != 'undef'

    - name: Ensure libvirt is installed
      ansible.builtin.dnf:
        name:
          - libvirt
          - qemu-kvm
          - libguestfs-tools
          - python3-libvirt
          - virt-install
          - python3-lxml
          - guestfs-tools
          - firewalld
        state: present

    - name: Ensure libvirtd service is running and enabled
      ansible.builtin.service:
        name: libvirtd
        state: started
        enabled: true

    - name: Ensure firewalld service is running and enabled
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Add user to libvirt group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: libvirt
        append: true

    - name: Download VM OS Image
      ansible.builtin.get_url:
        url: "{{ vm_os_image }}"
        dest: "/tmp/my_os_image.qcow2"
        mode: "0644"

    - name: Get MD5 checksum of a file
      ansible.builtin.stat:
        path: "/tmp/my_os_image.qcow2"
        checksum_algorithm: md5
      register: file_stat

    - name: Display the MD5 checksum
      ansible.builtin.debug:
        msg: "The MD5 checksum is {{ file_stat.stat.checksum }}"
      when: file_stat.stat.exists

    - name: Copy image to libvirt directory
      ansible.builtin.copy:
        src: "/tmp/my_os_image.qcow2"
        dest: "/var/lib/libvirt/images/{{ vm_name }}.qcow2"
        remote_src: true
        owner: qemu
        group: qemu
        mode: "0660"
      register: copy_results

    - name: Check if the VM is already defined
      ansible.builtin.command:
        cmd: "virsh dominfo {{ vm_name }}"
      register: vm_definition_check
      failed_when: false
      changed_when: false

    - name: Define the VM
      ansible.builtin.template:
        src: "templates/nested_vm_def.xml.j2"
        dest: "/tmp/{{ vm_name }}.xml"

    # Not using community.libvirt.virt module because it isn't in the stock supported-ee collections.
    - name: Define the VM in libvirt using virsh
      ansible.builtin.command:
        cmd: "virsh define /tmp/{{ vm_name }}.xml"
      when: vm_definition_check.rc != 0

    - name: Check if the VM is already started
      ansible.builtin.command:
        cmd: "virsh domstate {{ vm_name }}"
      register: vm_state_check
      failed_when: false
      changed_when: false

    - name: Start the VM
      ansible.builtin.command:
        cmd: "virsh start {{ vm_name }}"
      when: vm_state_check.stdout | trim != 'running'

    - name: Gather DHCP IP address of the VM
      ansible.builtin.command: >
        virsh domifaddr --domain {{ vm_name }}
      register: virsh_output
      changed_when: false
      until: virsh_output.stdout_lines | length >= 3
      retries: 5
      delay: 5

    - name: Parse and set the VM IP address from virsh output
      ansible.builtin.set_fact:
        vm_ip: "{{ virsh_output.stdout_lines[2] | regex_search('[0-9]{1,3}(?:[.][0-9]{1,3}){3}') }}"

    - name: Fail if VM IP address could not be found
      ansible.builtin.fail:
        msg: "Could not find a DHCP IP address for VM: {{ vm_name }}. Ensure the VM is running."
      when: vm_ip is none or vm_ip == ""

    - name: Enable IP masquerading on the host firewall
      ansible.posix.firewalld:
        zone: public
        masquerade: true
        permanent: true
        state: enabled
      notify: Reload firewalld

    - name: Enable SSH and HTTP services on the host firewall
      ansible.posix.firewalld:
        zone: public
        service: "{{ item }}"
        permanent: true
        state: enabled
      loop:
        - ssh
        - http
      notify: Reload firewalld

    - name: Allow TCP port 8080 through the host firewall
      ansible.posix.firewalld:
        zone: public
        port: 8080/tcp
        permanent: true
        state: enabled
      notify: Reload firewalld

    - name: Configure port forwarding from host to VM
      ansible.posix.firewalld:
        zone: public
        port_forward: 
          - port: "{{ host_port }}"
            proto: tcp
            toaddr: "{{ vm_ip }}"
            toport: "{{ vm_port }}"
        permanent: true
        state: enabled
      notify: Reload firewalld

    - name: Enable IPv4 forwarding in sysctl
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: true
        state: present
        reload: true

  handlers:
    - name: Reload firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded
