---
- name: Create a Nested VM on a RHEL Host
  hosts: "{{ _hosts | default(omit)  }}"
  become: true

  vars:
    host_port: "{{ _host_port | default(80) }}"
    vm_port: "{{ _vm_port | default(80) }}"

  tasks:
    - name: Check for vars
      ansible.builtin.assert:
        that:
          - vm_name is defined
          - vm_name != ''
          - vm_name != 'undef'
          - vm_os_image is defined
          - vm_os_image != ''
          - vm_os_image != 'undef'
          - vm_bridge is defined
          - vm_bridge != ''
          - vm_bridge != 'undef'
          - vm_ip is defined
          - vm_ip != ''
          - vm_ip != 'undef'
        msg: "Required variables not set. Please provide vm_name, vm_os_image, and vm_bridge."

    - name: Ensure libvirt is installed
      ansible.builtin.dnf:
        name:
          - libvirt
          - qemu-kvm
          - libguestfs-tools
          - python3-libvirt
          - virt-install
          - python3-lxml
          - guestfs-tools
          - firewalld
        state: present

    - name: Ensure libvirtd service is running and enabled
      ansible.builtin.service:
        name: libvirtd
        state: started
        enabled: true

    - name: Ensure firewalld service is running and enabled
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Add user to libvirt group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: libvirt
        append: true

    - name: Download VM OS Image
      ansible.builtin.get_url:
        url: "{{ vm_os_image }}"
        dest: "/tmp/my_os_image.qcow2"
        mode: "0644"

    - name: Copy image to libvirt directory
      ansible.builtin.copy:
        src: "/tmp/my_os_image.qcow2"
        dest: "/var/lib/libvirt/images/{{ vm_name }}.qcow2"
        remote_src: true
        owner: qemu
        group: qemu
        mode: "0660"
      register: copy_results

    - name: Create network configuration file in a temporary location
      ansible.builtin.copy:
        dest: "/tmp/enp1s0.nmconnection"
        owner: root
        group: root
        mode: '0644'
        content: |
          [connection]
          id=enp1s0
          type=ethernet
          interface-name=enp1s0

          [ipv4]
          address1={{ vm_ip }},{{ vm_gateway | default('10.0.1.1') }}
          dns={{ vm_dns | default('10.0.0.2') }};
          method=manual

    - name: Inject NetworkManager configuration file into guest image
      ansible.builtin.command: >
        virt-customize -a /var/lib/libvirt/images/{{ vm_name }}.qcow2
        --hostname {{ vm_name }}
        --copy-in /tmp/enp1s0.nmconnection:/etc/NetworkManager/system-connections
        --run-command 'chmod 600 /etc/NetworkManager/system-connections/enp1s0.nmconnection'
        --selinux-relabel
      register: virt_custom_result
      changed_when: virt_custom_result.rc == 0

    - name: Check if the VM is already defined
      ansible.builtin.command:
        cmd: "virsh dominfo {{ vm_name }}"
      register: vm_definition_check
      failed_when: false
      changed_when: false

    - name: Define the VM
      ansible.builtin.template:
        src: "templates/nested_vm_def.xml.j2"
        dest: "/tmp/{{ vm_name }}.xml"
        owner: root
        group: root
        mode: "0644"

    # NOTE: Through out this playbook we are not using community.libvirt.virt
    # module because it isn't in the stock supported-ee collections.
    - name: Define the VM in libvirt using virsh
      ansible.builtin.command:
        cmd: "virsh define /tmp/{{ vm_name }}.xml"
      when: vm_definition_check.rc != 0
      register: vm_define_result
      changed_when: vm_define_result.rc == 0

    - name: Check if the VM is already started
      ansible.builtin.command:
        cmd: "virsh domstate {{ vm_name }}"
      register: vm_state_check
      failed_when: false
      changed_when: false

    - name: Start the VM
      ansible.builtin.command:
        cmd: "virsh start {{ vm_name }}"
      when: vm_state_check.stdout | trim != 'running'
      register: vm_start_result
      changed_when: vm_start_result.rc == 0
