---
- name: Delete a Nested VM on a RHEL Host
  hosts: "{{ _hosts | default(omit)  }}"
  become: true
  gather_facts: false
  vars:
    host_port: "{{ _host_port | default(8080) }}"
    vm_port: "{{ _vm_port | default(80) }}"

  tasks:
    - name: Check for vars
      ansible.builtin.assert:
        that:
          - vm_name is defined
          - vm_name != ''
          - vm_name != 'undef'

    - name: Check the execution state of the VM
      ansible.builtin.command: virsh domstate {{ vm_name }}
      register: vm_state_check
      failed_when: false
      changed_when: false

    - name: Set a boolean fact for readability
      ansible.builtin.set_fact:
        is_vm_defined: "{{ vm_state_check.rc == 0 }}"
        is_vm_running: "{{ vm_state_check.rc == 0 and 'running' in vm_state_check.stdout }}"

    - name: Cleanup VM Networking if VM is Running
      when: is_vm_running
      block:
        - name: Gather DHCP IP address of the VM
          ansible.builtin.command: >
            virsh domifaddr {{ vm_name }}
          register: virsh_output
          changed_when: false

        - name: Parse and set the VM IP address from virsh output
          ansible.builtin.set_fact:
            vm_ip: "{{ (virsh_output.stdout | regex_search('\\b(?:[0-9]{1,3}\\\\.){3}[0-9]{1,3}\\b')) }}"

        - name: Fail if VM IP address could not be found
          ansible.builtin.fail:
            msg: "Could not find a DHCP IP address for VM: {{ vm_name }}. Ensure the VM is running."
          when: vm_ip is none or vm_ip == ""

        - name: Un-Configure port forwarding from host to VM
          ansible.posix.firewalld:
            zone: "public"
            forward_port: "port={{ host_port }}:proto=tcp:toport={{ vm_port }}:toaddr={{ vm_ip }}"
            permanent: true
            state: absent
          when: vm_ip is defined and vm_ip != ""
          notify: Reload firewalld

    - name: Stop and Undefine the VM if it is defined
      when: is_vm_defined
      block:
        - name: Stop the VM
          ansible.builtin.command:
            cmd: "virsh destroy {{ vm_name }}"
          when: is_vm_running

        - name: Undefine the VM in libvirt using virsh
          ansible.builtin.command:
            cmd: "virsh undefine {{ vm_name }}"

    - name: Clean up the Temp VM image file if it exists
      ansible.builtin.file:
        path: "/tmp/my_os_image.qcow2"
        state: absent

    - name: Clean up the VM Definition XML file if it exists
      ansible.builtin.file:
        path: "/tmp/{{ vm_name }}.xml"
        state: absent

    - name: Cleanup vm image file if it exists
      ansible.builtin.file:
        path: "/var/lib/libvirt/images/{{ vm_name }}.qcow2"
        state: absent

  handlers:
    - name: Reload firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded
