---
- name: Delete a Nested VM on a RHEL Host
  hosts: "{{ _hosts | default(omit)  }}"
  become: true
  gather_facts: false
  vars:
    host_port: "{{ _host_port | default(8080) }}"
    vm_port: "{{ _vm_port | default(80) }}"

  tasks:
    - name: Check for vars
      ansible.builtin.assert:
        that:
          - vm_name is defined
          - vm_name != ''
          - vm_name != 'undef'

    - name: Check the execution state of the VM
      ansible.builtin.command: virsh domstate {{ vm_name }}
      register: vm_state_check
      failed_when: false
      changed_when: false

    - name: Set a boolean fact for readability
      ansible.builtin.set_fact:
        is_vm_defined: "{{ vm_state_check.rc == 0 }}"
        is_vm_running: "{{ vm_state_check.rc == 0 and 'running' in vm_state_check.stdout }}"

    - name: Cleanup VM Networking if VM is Running
      when: is_vm_running
      block:
        - name: Get the VM MAC address from libvirt
          ansible.builtin.shell: |
            set -o pipefail
            virsh domiflist {{ vm_name }} | awk 'NR>2 {print $5}' | head -n 1
          args:
            executable: /bin/bash
          register: vm_mac
          changed_when: false

        - name: Wait for VM network initialization and locate ARP entry
          block:
            - name: Force host to update ARP table and extract VM IP
              ansible.builtin.shell: |
                set -o pipefail
                # Ping the network broadcast or check neighbors to wake up stale entries
                ip neighbor show > /dev/null

                # Search the local ARP / Neighbor cache for the specific MAC address
                ip neighbor show | grep -i "{{ vm_mac.stdout | trim }}" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}'
              args:
                executable: /bin/bash
              register: arp_output
              # Loop configuration: Retries every 5 seconds for up to 1 minute
              until: arp_output.stdout | trim != ""
              retries: 3
              delay: 5
              changed_when: false
              failed_when:: false

            - name: Store the found IP address
              ansible.builtin.set_fact:
                vm_ip: "{{ arp_output.stdout | trim }}"

        - name: Un-Configure port forwarding from host to VM
          ansible.posix.firewalld:
            zone: "public"
            forward_port: "port={{ host_port }}:proto=tcp:toport={{ vm_port }}:toaddr={{ vm_ip }}"
            permanent: true
            state: absent
          when: vm_ip is defined and vm_ip != ""
          notify: Reload firewalld

    - name: Stop and Undefine the VM if it is defined
      when: is_vm_defined
      block:
        - name: Stop the VM
          ansible.builtin.command:
            cmd: "virsh stop {{ vm_name }}"
          when: is_vm_running

        - name: Undefine the VM in libvirt using virsh
          ansible.builtin.command:
            cmd: "virsh undefine {{ vm_name }}"

    - name: Clean up the Temp VM image file if it exists
      ansible.builtin.file:
        path: "/tmp/my_os_image.qcow2"
        state: absent

    - name: Clean up the VM Definition XML file if it exists
      ansible.builtin.file:
        path: "/tmp/{{ vm_name }}.xml"
        state: absent

    - name: Cleanup vm image file if it exists
      ansible.builtin.file:
        path: "/var/lib/libvirt/images/{{ vm_name }}.qcow2"
        state: absent

  handlers:
    - name: Reload firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded
